name: 'Setup Node.js and Install Dependencies'
description: 'Sets up Node.js environment and installs dependencies'

runs:
  using: 'composite'
  steps:
    - name: Check if .nvmrc exists
      id: check_nvmrc
      shell: bash
      run: |
        if [ -f ".nvmrc" ]; then
          echo "nvmrc_exists=true" >> $GITHUB_OUTPUT
          echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        else
          echo "nvmrc_exists=false" >> $GITHUB_OUTPUT
          echo "node_version=20" >> $GITHUB_OUTPUT
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.check_nvmrc.outputs.node_version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci 