# wrangler.toml
name = "10x-cards"
compatibility_date = "2024-01-01"

# Konfiguracja Workers
workers_dev = true

[site]
bucket = "./dist"

# Define KV namespace for session storage
# For CI/CD, we're using the preview key to avoid requiring a real KV namespace
kv_namespaces = [
  { binding = "SESSION", preview_id = "SESSION" } 
]

# Zmienne w produkcji są definiowane za pomocą Cloudflare Dashboard
# lub przez wrangler secrets
[vars]
CLOUDFLARE_KV_BINDING_SESSION = "true"

[[env.production.vars]]
SUPABASE_URL = ""
PUBLIC_SUPABASE_URL = ""

# Secrets are defined in the Cloudflare dashboard or using wrangler
# wrangler secret put SUPABASE_KEY
# wrangler secret put PUBLIC_SUPABASE_ANON_KEY
# wrangler secret put OPENROUTER_API_KEY